---
title: "GlobalZBio_BRT"
author: "Jasmine Fowler-Morrow"
date: '2022-11-01'
output: pdf_document
---


```{r}
############ Preliminaries ################
library(xgboost)
library(caret)
library(tidyverse)
library(raster)
library(ggplot2)
library(terra)
library(sf)
library(dplyr)
library(patchwork)

dat <- readRDS("Data/GlobalBiomassData.rds") 
#dat2 <- readRDS("Data/GlobalBiomassDataESM.rds") ESM data? 

# Reduce some extreme values, and remove 5 zero values  
dat <- dat %>% 
  mutate(
    Mesh = replace(Mesh, Mesh > 1000, 1000),
    Depth = replace(Depth, Depth > 1500, 1500),
    Depth2 = Depth/1000, #scaled depth variable 
    Bathy = replace(Bathy, Bathy > 7000, 7000),
    SST = replace(SST, SST > 31, 31),
    Biomass = replace(Biomass, Biomass > 10000, 10000)) %>%
  filter(Biomass > 0)
```

```{r}
#-------------------------------------------------------
             # TRAIN TEST SPLIT
#-------------------------------------------------------
#make this example reproducible
set.seed(0)

#split into training (80%) and testing set (20%)
#by default, the split uses percentiles of y and has well balanced pred
parts = createDataPartition(dat$Biomass, p = .8, list = F)

# only include a few predictors for now 
train = as.data.frame(dat[parts,
                          c("Biomass","BiomassMethod","DOY","Depth",
                            "Bathy","SST","Chl","TimeLocal","Mesh",
                            "DatasetID","Gear")]) 
test = as.data.frame(dat[-parts, 
                         c("Biomass","BiomassMethod","DOY","Depth",
                           "Bathy","SST","Chl","TimeLocal","Mesh",
                           "DatasetID","Gear")])  

#define predictor and response variables in training set
train_x = data.matrix(train[, -1]) #column 1 is biomass 
train_y = train[,1]

#define predictor and response variables in testing set
test_x = data.matrix(test[, -1])
test_y = test[, 1]

#define final training and testing sets
xgb_train = xgb.DMatrix(data = train_x, label = train_y)
xgb_test = xgb.DMatrix(data = test_x, label = test_y)

#define watchlist
watchlist = list(train=xgb_train, test=xgb_test)
```


```{r}
#---------------------------------------------------------
        # Final model performance metrics 
#---------------------------------------------------------
#1000 rounds, eta = 0.1, max depth 6, min child 5

## Read in final BRT model
model <- readRDS("./Output/BRT_final.rds") 
y_pred <- predict(model, test_x)
cor(y_pred, test_y) # 0.594 R^2 = 0.35
cor.test(y_pred, test_y)

y_pred <- predict(model, train_x)
cor(y_pred, train_y) #0.724 R^2 = 0.52

y_pred <- predict(model, data.matrix(as.data.frame(dat[c("BiomassMethod",
                                        "DOY","Depth","Bathy",
                                        "SST","Chl","TimeLocal",
                                        "Mesh","DatasetID","Gear")])))
cor(y_pred, dat$Biomass)^2 #R^2 = 0.49
cor.test(y_pred, dat$Biomass) #yay p<2.2e-16
```

```{r}
#-------------------------------------------------------
            # check accuracy metrics
#-------------------------------------------------------
mean((test_y - y_pred)^2) #mse
MAE(test_y, y_pred) #mae

#average difference between predicted and observed values in test set
RMSE(test_y, y_pred) #rmse

model$evaluation_log

## Variable importance plot
vip::vip(model)
#ggsave("./Figures/BRT_pred_importance.png")
```

```{r}
#-------------------------------------------------------
           #set up data to predict biomass  
#-------------------------------------------------------

## IMPORT BATHYMETRY DATA AND ORIENT LATITUDES TO BE SOUTH TO NORTH
bathy_data <- readRDS(file.path("Data","Bathy_raster_oneDeg.rds"))
bathy_matrix <- t(as.matrix(bathy_data$Bathy))
bathy_matrix <- bathy_matrix[,180:1]

## Calculate areas of grid cells
glob_area <- t(as.matrix(raster::area(raster())))

##### Set up array to make predictions and save outputs ######
save_array <- array(NA, dim = c(12,13,64800)) 
# matches month x variable x bathy #
dimnames(save_array)[[1]] <- c("Jan", "Feb", "Mar", "Apr", 
                               "May", "Jun", "Jul", "Aug", 
                               "Sep", "Oct", "Nov", "Dec")
dimnames(save_array)[[2]] <- c("Longitude", "Latitude", 
                              "BiomassMethod","DOY","Depth",
                              "Bathy","SST","Chl","TimeLocal","Mesh",
                               "DatasetID","Gear", "BRT_Mesozoo")

## Set mesh, start depth and time of day
save_array[,"Mesh",] <- 0 # we might want this at 0/25??
save_array[,"Depth",] <- 1
save_array[,"TimeLocal",] <- 0

## Final output matrix, with non-important factors removed
save_array2 <- save_array[,-c(3,4,5,9,10,11,12),] 
#keeps lon, lat, bathy, predictions

#Longitude x Latitude matrix
lonlat <- as.matrix(expand.grid("lons" = -179.5:179.5, 
                                "lats" = -89.5:89.5))

## Harmonic day of year for each month
days_of_year <- seq(15,365,30)

## Depth is set to surface, this can be changed to a vector of depths...
depth <- 0.5

```


```{r}
#----------------------------------------------
      # get predictions for every month 
#----------------------------------------------

for (k in 1:12){
  print(paste0("Now working on month ",k))
  
  ## Import current month (k) sst and chl climatology
  curr_sst <- 
    t(as.matrix(readRDS(list.files(
      path = './Data/',
      pattern = glob2rx(paste("SST*", 
                              dimnames(save_array)[[1]][k], "*", 
                              sep = "")), full.names = TRUE))))[, 180:1]
  curr_chl <- 
    t(as.matrix(readRDS(list.files(
      path = './Data/',
      pattern = glob2rx(paste("Chl*", 
                              dimnames(save_array)[[1]][k], 
                              "*", sep = "")), full.names = TRUE))))[, 180:1]
  
  ## Fill in this month's slice of save_array
  save_array[k, "Longitude", ] <- lonlat[, 1]
  save_array[k, "Latitude", ] <- lonlat[, 2]
  save_array[k, "Bathy", ] <- as.vector(bathy_matrix)
  
  save_array[k, "DOY", 1:64800] <- days_of_year[k] 
  
  save_array[k, "SST", ] <- as.vector(curr_sst)
  save_array[k, "Chl", ] <- as.vector(curr_chl)
  
  #Align SST and chlo maps with bathy (where bathy is land, mask sst and chlo)
  save_array[k, "SST", 
             which(is.na(save_array[k, "Bathy", ] == TRUE))] <- NA
  save_array[k, "Chl", 
             which(is.na(save_array[k, "Bathy", ] == TRUE))] <- NA
  
  # Convert to dataframe and add random effects factors and 0.5m depth for glmm prediction
  kk <- as.data.frame(t(save_array[k, , ])) #df of month k only 
  kk$BiomassMethod <- as.numeric(as.factor("Carbon"))
  kk$Gear <- as.numeric(as.factor("116"))
  kk$DatasetID <- as.numeric(as.factor("100"))
  kk$Depth <- depth
  
  ####### SURFACE LAYER PREDICTIONS ########
  # Get surface layer estimate
  kk$BRT_Mesozoo <- predict(model,
                             newdata = as.matrix(kk[,3:12]),
                            outputmargin = FALSE)
  
  
  ## Dump output into this month's time slice of save array2
  save_array2[k, "Longitude", ] <- as.vector(kk$Longitude)
  save_array2[k, "Latitude", ] <- as.vector(kk$Latitude)
  save_array2[k, "Bathy", ] <- as.vector(kk$Bathy)
  save_array2[k, "SST", ] <- as.vector(kk$SST)
  save_array2[k, "Chl", ] <- as.vector(kk$Chl)
  save_array2[k, "BRT_Mesozoo", ] <- as.vector(kk$BRT_Mesozoo)
  
  ## Make sure if SST or Chl are NA, prediction is also NA
  save_array2[k, "BRT_Mesozoo", 
             which(is.na(save_array2[k, "SST", ] == TRUE))] <- NA
  save_array2[k, "BRT_Mesozoo", 
             which(is.na(save_array2[k, "Chl", ] == TRUE))] <- NA
}
```

```{r}
## now change the way monthly predictions are stored for average maps
#average code but the arrays are tricky to work with so here we are

biomass_monthly <- data.frame(Jan = NA,Feb = NA,Mar = NA,
                              Apr = NA, May = NA, Jun = NA,
                              Jul = NA,Aug = NA,Sep = NA,
                              Oct = NA,Nov = NA,Dec = NA,
                              Longitude = lonlat[,1],
                              Latitude = lonlat[,2])

for (j in 1:12){
  biomass_monthly[,j] <- save_array2[j, "BRT_Mesozoo", ]
}

saveRDS(biomass_monthly, "./Output/monthly_biomass_predictions.rds")

```


```{r}
#--------------------------------------------------
        # Function to produce average biomass map
#--------------------------------------------------

## code to take an average over a few months and produce/save figure
monthly_mean_plot <- function(months){
  
  names <- colnames(biomass_monthly[,months])
  plot_name <- paste(names[1],names[3], sep = "-") #name to save plot
  
  #take mean over multiple months 
  biomass_monthly$mean <- rowMeans(biomass_monthly[,months], na.rm = T)
  
  ## plot with projection 
  kk_sf <- biomass_monthly %>%
    sf::st_as_sf(coords=c("Longitude", "Latitude"))
  
  lon_lat <- "+proj=longlat +datum=WGS84 +ellps=WGS84 +towgs84=0,0,0"
  
  sf::st_crs(kk_sf) <- lon_lat
  
  landmass <- rnaturalearth::ne_countries(scale = "large") %>% 
    sf::st_as_sf(crs = lon_lat)
  
  # Mollweide equal-area projection
  moll <- "+proj=moll +lon_0=0 +x_0=0 +y_0=0 +ellps=WGS84 +datum=WGS84 +units=m no_defs" 
  
  # Transform data using projection
  kk_transformed <- kk_sf %>%
    sf::st_transform(moll)
  
  # Transform the landmass to the same projection
  landmass <- landmass %>% 
    sf::st_transform(crs = moll)
  
  p <- ggplot() + 
    geom_sf(data = kk_transformed, aes(color = mean), size = 0.01) +
    geom_sf(data = landmass, fill = "grey20", color = NA, size = 0.01) +
    scale_color_viridis_c(trans = "log10",
                          na.value = "grey20",
                          name = expression(paste("Zooplankton biomass mg m"^-2)),
                          limits = c(0.1,10), oob = scales::squish) +
    theme_classic() +
    ggtitle(label = plot_name)
  
  return(p)
}

#monthly_mean_plot(c(12,1,2))
#ggsave("./Figures/Dec_Feb_surface_biomass.png")

```


```{r}
#------------------------------------------------
           #Produce seasonal biomass maps 
#------------------------------------------------

#Dec- Feb
p1 <- monthly_mean_plot(c(12,1,2))
#Mar - May
p2 <- monthly_mean_plot(c(3:5))
#Jun - Aug
p3 <- monthly_mean_plot(c(6:8))
#Sep - Nov
p4 <- monthly_mean_plot(c(9:11))

#combining them with incorrect colour scales is not a good visualisation 
(p1 | p2) / (p3 | p4) + plot_annotation(tag_levels = "A", tag_suffix = '. ') +
  plot_layout(guides = "collect") & theme(legend.position = "bottom", 
                                          plot.margin = margin(0.25,0.25,0.25,0.25),
                                          plot.title = element_text(size = 9),
                                          plot.tag = element_text(size = 9,
                                          hjust = -3, vjust = -3),)


ggsave(paste0("./Figures/","BRTseasonal_maps",".pdf"))


```

```{r}
## Additional: code to plot a single month biomass with projection 
kk_sf <- kk %>%
  sf::st_as_sf(coords=c("Longitude", "Latitude"))

lon_lat <- "+proj=longlat +datum=WGS84 +ellps=WGS84 +towgs84=0,0,0"

sf::st_crs(kk_sf) <- lon_lat

landmass <- rnaturalearth::ne_countries(scale = "large") %>% 
  sf::st_as_sf(crs = lon_lat)

# Mollweide equal-area projection
moll <- "+proj=moll +lon_0=0 +x_0=0 +y_0=0 +ellps=WGS84 +datum=WGS84 +units=m no_defs" 

# Transform data using projection
kk_transformed <- kk_sf %>%
  sf::st_transform(moll)

# Transform the landmass to the same projection
landmass <- landmass %>% 
  sf::st_transform(crs = moll)


ggplot() + 
  geom_sf(data = kk_transformed, aes(color = BRT_Mesozoo), size = 0.01) +
  geom_sf(data = landmass, fill = "grey20", color = NA, size = 0.01) +
  scale_color_viridis_c(trans = "log10",
                        na.value = "grey20",
                        name = expression(paste("Zooplankton biomass mg m"^-2)),
                        limits = c(0.1,10), oob = scales::squish) +
  theme_bw() 
ggsave("./Figures/year_surface_biomass.png")
```



```{r}
#-------------------------------------------------
  #Additional: plot the chlorophyll map for Jan
#-------------------------------------------------
 curr_chl <- 
    t(as.matrix(readRDS(list.files(
      path = './Data/',
      pattern = glob2rx(paste("Chl*", 
                              dimnames(save_array)[[1]][1], 
                              "*", sep = "")), full.names = TRUE))))[, 180:1]
colnames(curr_chl) <- -89.5:89.5

chl.df <- as.data.frame(cbind(long = -179.5:179.5, curr_chl))

chl.df <- chl.df %>%
  pivot_longer(-long, names_to = "lat", values_to = "Chl") 
  
chl.df$lat <- as.numeric(chl.df$lat)


lon_lat <- "+proj=longlat +datum=WGS84 +ellps=WGS84 +towgs84=0,0,0"

sf::st_crs(kk_sf) <- lon_lat

landmass <- rnaturalearth::ne_countries(scale = "large") %>% 
  sf::st_as_sf(crs = lon_lat)


ggplot() +  #gglot version of map 
  geom_raster(data = chl.df, aes(x = long, y = lat, fill = Chl)) +
  geom_sf(data = landmass, fill = "grey20", color = NA, size = 0.01) +
  scale_fill_viridis_c(trans = "log10",
                       limits = c(0.1,20), oob = scales::squish)


```

